name = "BrauerInduction"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["BrauerInduction"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
linter.style.header = false
linter.style.emptyLine = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "BrauerInduction"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "OldChallenge"

[[lean_lib]]
name = "Solution"
