import BrauerInduction.Projection

universe u v

open BigOperators

namespace BrauerInduction

/-!
# Brauer induction theorem

This file proves the linear-character form of Brauer induction.

The proof follows Bernstein's route.  The projection step proves that the
constant class function `1` lies in `BrauerSpanChar`.  Multiplying by the
character of a finite-dimensional representation shows that every representation
character lies in `BrauerSpanChar`.  The theorem
`BrauerSpanChar.le_BrauerSpanLin` then converts this to membership in the span
generated by characters induced from linear characters of Brauer-elementary
subgroups.
-/

/--
Brauer induction as an equality of class functions.

The character of any finite-dimensional representation is an integral linear
combination of characters induced from linear characters of Brauer-elementary
subgroups.
-/
theorem character_eq_sum_induced_linear_classFun
    {G : Type u} [Group G] [Finite G]
    {k : Type u} [Field k] [CharZero k] [IsAlgClosed k]
    (V : FDRep k G) :
    ∃ (ι : Type) (_ : Fintype ι)
      (ns : ι → ℤ) (Hs : ι → Subgroup G)
      (ψs : ∀ i, Hs i →* kˣ),
      (∀ i, IsBrauerElementary (Hs i)) ∧
      ClassFun.character V =
        ∑ i, ns i •
          ClassFun.character (FDRep.indLin (Hs i) (ψs i)) := by
  letI : Fintype G := Fintype.ofFinite G

  have h1 :
      (1 : ClassFun k G) ∈ BrauerSpanChar  :=
    BrauerInduction.one_mem_BrauerSpanChar

  have hV_char :
      ClassFun.character V ∈ BrauerSpanChar := by
    have hmul :
        ClassFun.character V * (1 : ClassFun k G)
          ∈ BrauerSpanChar := BrauerSpanChar.character_mul_mem V h1
    simpa [mul_one] using hmul

  have hV_lin :
      ClassFun.character V ∈ BrauerSpanLin :=
    BrauerSpanChar.le_BrauerSpanLin hV_char

  obtain ⟨ι, hι, ns, Hs, ψs, hElem, hsum⟩ :=
    exists_decomposition_of_mem_BrauerSpanLin
      (χ := ClassFun.character V) hV_lin

  exact ⟨ι, hι, ns, Hs, ψs, hElem, hsum⟩

/--
Brauer induction in representation-character notation.

This is the same decomposition as `character_eq_sum_induced_linear_classFun`,
rewritten using `FDRep.character` instead of `ClassFun.character`.
-/
theorem character_eq_sum_induced_linear
    {G : Type u} [Group G] [Finite G]
    {k : Type u} [Field k] [CharZero k] [IsAlgClosed k]
    (V : FDRep k G) :
    ∃ (ι : Type) (_ : Fintype ι)
      (ns : ι → ℤ) (Hs : ι → Subgroup G)
      (ψs : ∀ i, Hs i →* kˣ),
      (∀ i, IsBrauerElementary (Hs i)) ∧
      V.character =
        ∑ i, ns i • (FDRep.indLin (Hs i) (ψs i)).character := by

  obtain ⟨ι, hι, ns, Hs, ψs, hElem, hsum⟩ := character_eq_sum_induced_linear_classFun V

  refine ⟨ι, hι, ns, Hs, ψs, hElem, ?_⟩

  ext g
  simpa [ClassFun.char_apply, ClassFun.sum_apply, ClassFun.smul_apply] using
    congrArg (fun F : ClassFun k G => F g) hsum

end BrauerInduction
